on:
  pull_request:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created, edited, deleted]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: test-hook-neurade/hook-backend@v6
        env:
          BACKEND_URL: http://103.237.147.55:8085
          SECRET_TOKEN: trucxinh
